name: bandapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  get: ^4.6.1
  
  get_storage: ^2.0.3
  
  flutter_screenutil: ^5.4.0+1
  
  pin_code_fields: ^7.4.0
  
  video_player: ^2.5.1

  chewie: ^1.7.4
    
  step_progress_indicator: ^1.0.2
  
  syncfusion_flutter_charts: ^20.4.48
  
  flutter_custom_clippers: ^2.1.0
  
  flutter_svg: 
  
  flutter_svg_provider: ^1.0.3
  
  http: ^0.13.5

  flutter_easyloading: ^3.0.5

  persistent_bottom_nav_bar: ^4.0.2
  
  flutter_countdown_timer: ^4.1.0
  
  shared_preferences: ^2.0.15
  
  flutter_spinkit: ^5.1.0
  
  logger: ^1.2.1
  
  internet_connection_checker: ^1.0.0+1
  
  url_launcher: ^6.1.5
  
  speech_to_text: ^6.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/svg/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
    - family: RobotoBold
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
    
    - family: RobotFlexRegular
      fonts:
        - asset: assets/fonts/Roboto_Flex/RobotoFlex-Regular.ttf

    - family: PlusJakartaSansRegular
      fonts:
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-Regular.ttf
    - family: PlusJakartaSansMedium
      fonts:
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-Medium.ttf
    - family: PlusJakartaSansBold
      fonts:
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-Bold.ttf
    - family: PlusJakartaSansExtraBold
      fonts:
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-ExtraBold.ttf
    - family: NotoSerif
      fonts:
        - asset: assets/fonts/NotoSerifLao-VariableFont_wdth,wght.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
